//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linguistico.NET_Mobile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class dict_resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal dict_resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Linguistico.NET_Mobile.dict_resources", typeof(dict_resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abacus	počitadlo	
        ///abandon	opustit	
        ///abandon	opustit; zanechat	
        ///abandoned	opuštěný	
        ///abandonment	zřeknutí se	
        ///abase	ponížit	
        ///abasement	ponížení	
        ///abash	zahanbit; uvést do rozpaků; přivést do rozpaků	
        ///abate	slábnout	
        ///abatement	snížení; zmenšení	
        ///abbey	opatství	
        ///abbreviate	zkracovat; zkrátit	
        ///abbreviation	zkratka	
        ///abdicate	abdikovat	
        ///abdication	abdikace	
        ///abdomen	břicho	
        ///abduct	unést	
        ///abduction	únos	
        ///aberration	odchylka; úchylka	
        ///aberration	zkreslení	
        ///abeyance	odklad	
        ///abhor	hrozit se	
        ///abhorrence	odpor; nechuť	
        ///abh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string english_czech {
            get {
                return ResourceManager.GetString("english_czech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abandon	abandonner; délaisser; quitter	
        ///abandoned	abandonné	
        ///abandonment	abandon	
        ///abase	abaisser; avilir; dégrader; humilier	
        ///abasement	humiliation	
        ///abatement	abaissement; diminution; réduction	
        ///abbey	abbaye	
        ///abbreviate	abréger; raccourcir; rogner; réduire; écourter	
        ///abbreviation	abréviation	
        ///abdication	abdication	
        ///abdomen	abdomen; ventre	
        ///abduction	rapt; enlèvement	
        ///aberration	aberration; déviation	
        ///aberration	distorsion; déformation	
        ///abeyance	ajournement; renvoi	
        ///abhorrence	aversion; répulsion; répugnance [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string english_french {
            get {
                return ResourceManager.GetString("english_french", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abandon	verlassen; zurücklassen	
        ///abandoned	verlassen	
        ///abandonment	Aufgabe; Verzicht	
        ///abase	erniedrigen; demütigen; entwürdigen	
        ///abasement	Demütigung; Erniedrigung	
        ///abatement	Abnahme; Verringerung	
        ///abbey	Abtei	
        ///abbreviate	abkürzen; verkürzen	
        ///abbreviation	Abkürzung	
        ///abdication	Abdankung	
        ///abdomen	Bauch; Unterleib; Leib	
        ///abduction	Entführung	
        ///aberration	Aberration; Abweichung	
        ///aberration	Verzerrung	
        ///abeyance	Aufschub; Verschiebung	
        ///abhorrence	Abscheu; Ekel	
        ///abhorrent	obszön; unzüchtig; widerlich	
        ///abide	aushalt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string english_german {
            get {
                return ResourceManager.GetString("english_german", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abandon	abandonar; aborrecer; desamparar	
        ///abandoned	abandonado	
        ///abandonment	abdicación	
        ///abase	abatir; degradar; humillar; rebajar	
        ///abasement	degradación; envilecimiento; humillación	
        ///abatement	baja; disminución; rebaja; reducción	
        ///abbey	abadía	
        ///abbreviate	abreviar; acortar	
        ///abbreviation	abreviación; abreviatura	
        ///abdication	abdicación	
        ///abdomen	abdomen; vientre; barriga	
        ///abduction	abducción; rapto; secuestro	
        ///aberration	desviación; desvío; aberración	
        ///abeyance	suspensión	
        ///abhorrence	aborrecimiento; aversión;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string english_spanish {
            get {
                return ResourceManager.GetString("english_spanish", resourceCulture);
            }
        }
    }
}
